'use client'

import { useMemo, useState } from 'react'
import { Plus, Clapperboard, X, Save, Film, Circle, MoreHorizontal } from 'lucide-react'
import { useStoryStore } from '../../store/useStoryStore'
import { nanoid } from 'nanoid'

export default function ArcTimeline() {
  const { arcs, currentArcId, arcGraphs, setCurrentArc, addArc, deleteArc, isPresenting } = useStoryStore()
  const [showNew, setShowNew] = useState(false); const [title,setTitle]=useState(''); const [description,setDescription]=useState('')
  const currentGraph=arcGraphs[currentArcId]; const nodeCount=currentGraph?.nodes.length||0; const edgeCount=currentGraph?.edges.length||0
  const arcStats=useMemo(()=>arcs.map(a=>({id:a.id,nodes:arcGraphs[a.id]?.nodes.length||0,edges:arcGraphs[a.id]?.edges.length||0})),[arcs,arcGraphs])
  const create=async()=>{if(!title.trim())return; await addArc(`arc-${nanoid(5)}`,title.trim(),description.trim());setTitle('');setDescription('');setShowNew(false)}
  return <>
    <div className={`h-28 border-t border-white/5 bg-[#0b0b0d] px-6 z-20 relative flex items-center gap-5 transition-all duration-500 ${isPresenting?'translate-y-full opacity-0 invisible':''}`}>
      <div className="flex items-center gap-3 border-r border-white/5 pr-6"><div className="rounded-xl bg-red-500/10 p-2.5 text-red-500"><Clapperboard size={18}/></div><div><h2 className="text-[10px] font-black uppercase tracking-widest">Arc Timeline</h2><p className="text-[8px] font-bold uppercase text-zinc-600">Story sequence</p></div></div>
      <div className="flex flex-1 items-center gap-3 overflow-x-auto pb-1">{arcs.map((arc,i)=>{const stat=arcStats.find(s=>s.id===arc.id)!;const active=arc.id===currentArcId;return <button key={arc.id} onClick={()=>setCurrentArc(arc.id)} className={`group relative min-w-[210px] rounded-2xl border p-3 text-left transition-all ${active?'border-red-500/50 bg-red-500/10 shadow-lg shadow-red-500/5':'border-white/5 bg-white/[.03] hover:border-white/15'}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${active?'animate-pulse bg-red-500':'bg-zinc-700'}`}/><span className="text-[8px] font-black uppercase tracking-widest text-zinc-600">Arc {i+1}</span><span className="ml-auto text-[8px] text-zinc-600">{stat.nodes} scenes</span></div><h3 className={`mt-2 truncate text-[11px] font-bold uppercase ${active?'text-white':'text-zinc-400'}`}>{arc.title}</h3><p className="mt-1 truncate text-[8px] text-zinc-600">{arc.description||'No summary'}</p><div className="mt-3 flex items-center gap-3 text-[8px] uppercase tracking-wider text-zinc-600"><span className="flex items-center gap-1"><Film size={10}/> {stat.nodes} nodes</span><span className="flex items-center gap-1"><Circle size={8}/> {stat.edges} links</span></div><span onClick={(e)=>{e.stopPropagation();if(confirm('Delete this Arc? All nodes will be lost.'))deleteArc(arc.id)}} className="absolute right-2 top-2 hidden rounded p-1 text-zinc-600 hover:bg-red-500/10 hover:text-red-400 group-hover:block"><X size={11}/></span></button>})}<button onClick={()=>setShowNew(true)} className="flex h-[92px] min-w-[70px] items-center justify-center rounded-2xl border border-dashed border-white/10 text-zinc-500 hover:border-white/25 hover:bg-white/5 hover:text-white"><Plus size={20}/></button></div>
      <div className="border-l border-white/5 pl-5"><div className="mb-2 text-right text-[8px] font-bold uppercase tracking-widest text-zinc-600">Current Arc</div><div className="text-right text-xs font-black text-white">{nodeCount} <span className="font-normal text-zinc-600">scenes</span></div><div className="text-right text-[8px] uppercase text-zinc-600">{edgeCount} connections</div></div>
    </div>
    {showNew&&<div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div className="relative w-full max-w-md rounded-2xl border border-white/10 bg-[#0d0d0d] p-6 shadow-2xl"><button onClick={()=>setShowNew(false)} className="absolute right-4 top-4 text-zinc-500 hover:text-white"><X size={18}/></button><h2 className="flex items-center gap-3 text-lg font-black uppercase tracking-widest"><Plus className="text-red-500"/> New Arc</h2><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} placeholder="Arc title" className="mt-6 w-full rounded-xl border border-white/5 bg-white/5 px-4 py-3 text-sm outline-none focus:border-red-500/50"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Arc summary" className="mt-3 h-24 w-full resize-none rounded-xl border border-white/5 bg-white/5 px-4 py-3 text-sm outline-none focus:border-red-500/50"/><div className="mt-5 flex gap-3"><button onClick={()=>setShowNew(false)} className="flex-1 rounded-xl border border-white/5 py-3 text-[10px] font-black uppercase text-zinc-500">Cancel</button><button onClick={create} className="flex-1 rounded-xl bg-white py-3 text-[10px] font-black uppercase text-black"><Save size={14} className="mr-2 inline"/>Create Arc</button></div></div></div>}
  </>
}
